name: Deploy Shiny app

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update apt-get
        run: |
          sudo apt-get update

      - name: Install curl
        run: |
          sudo apt-get install libcurl4-openssl-dev

      - uses: r-lib/actions/setup-r@v1

      - name: Deploy
        env:
          RSHINY_TOKEN: ${{ secrets.RSHINY_TOKEN}}
          RSHINY_SECRET: ${{ secrets.RSHINY_SECRET}}
        run: source("R/deploy.R")
        shell: Rscript {0} 
