name: Deploy Shiny app

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1


      - name: Deploy
        env:
          RSHINY_TOKEN: ${{ secrets.RSHINY_TOKEN}}
          RSHINY_SECRET: ${{ secrets.RSHINY_SECRET}}
        run: R R\deploy.R